Buyt 12 solving issues
BuyMeTicketTeam/FindMeTicket pull request #27
Opened 2024-01-25 09:01 UTC by KirilllP

pull request

2024-01-29 06:42 UTC, VKuzmich approved these changes
good job!

2024-01-29 20:09 UTC, mishaakamichael999 commented
Problems to be solved:
1. n+1 
2. no tickets scraped out of INFOBUS service

2024-02-12 16:08 UTC, VKuzmich requested changes
please resolve conflicts

2024-02-13 16:26 UTC, mishaakamichael999 approved these changes

2024-02-13 16:35 UTC, maks2708 approved these changes

2024-02-14 13:52 UTC, merged